"""Create cast_and_crew table.

Revision ID: ba5587d2a3b9
Revises: 5ddc5fbd2eae
Create Date: 2025-07-04 23:00:24.769742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5587d2a3b9'
down_revision: Union[str, Sequence[str], None] = '5ddc5fbd2eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast_and_crew',
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('stage_name', sa.String(length=256), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_and_crew_id'), 'cast_and_crew', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cast_and_crew_id'), table_name='cast_and_crew')
    op.drop_table('cast_and_crew')
    # ### end Alembic commands ###
